name: Shellcheck Action

on:
  push:
    paths:
      - '**/*.sh'
      - '.shellcheckrc'
      - '.github/workflows/shellcheck.yml'

permissions:
  contents: read

jobs:
  build:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Shellcheck
        uses: step-security/action-shellcheck@v2
