name: Spellcheck Action

on:
  # Enabling manual test
  # REF: https://stackoverflow.com/questions/58933155/manual-workflow-triggers-in-github-actions
  workflow_dispatch:
  push:
    paths:
      - '**/*.md'
      - 'spellcheck.yaml'
      - 'wordlist.txt'
      - '.github/workflows/spelling_action.yml'

permissions:
  contents: read

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Spellcheck
        uses: step-security/spellcheck-github-actions@v0
        with:
          source_files: README.md CHANGELOG.md
          task_name: Markdown
          output_file: spellcheck-output.txt

      - name: Archive spellcheck output
        uses: actions/upload-artifact@v7
        if: '!cancelled()'
        with:
          name: Spellcheck artifact
          path: spellcheck-output.txt
